#! /bin/sh

OPTIND=1

# Initialize our variables:
VERBOSE=0
NOCLEAN=0
TARGET=iface.$1
PARCLASS=TestClass



# Generate the temporary file to expand macros
TMPFILE="_iface.$1"
echo '#include "parse_interface.hpp"'                       >  $TMPFILE
echo "#define _parclass_ $PARCLASS"                         >> $TMPFILE
echo 'namespace pop{'                                       >> $TMPFILE
echo 'class _parclass_ : public pop::interface'             >> $TMPFILE
echo '{'                                                    >> $TMPFILE
echo 'public:'                                              >> $TMPFILE
sed -n 's|.\s//##||p' $1                                    >> $TMPFILE
echo '};'                                                   >> $TMPFILE
echo '}'                                                    >> $TMPFILE

# Generate the interface file
echo '#include "class/interface.hpp"'       >  $TARGET
echo '#include "'$1'"'                      >> $TARGET
c++ -I../parser -E $TMPFILE | grep -v "^# " >> $TARGET

rm $TMPFILE

astyle -nToO --style=allman $TARGET
